# Generated by Django 4.2 on 2026-01-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.CharField(choices=[('youtube', 'YouTube (embed URL)'), ('file', 'Uploaded file')], default='youtube', max_length=16),
        ),
    ]
