services:
  - type: web
    name: karyor
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn cattle.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: karyor
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "karyor.com,www.karyor.com,cattle-1.onrender.com,localhost,127.0.0.1"
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
        sync: false
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false