# Generated by Django 4.2 on 2026-01-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slot',
            field=models.CharField(choices=[('hero', 'Hero'), ('mini', 'Mini Slider')], default='hero', help_text='Where this banner is used', max_length=10, verbose_name='slot'),
        ),
    ]
