# Generated by Django 4.2 on 2026-01-23 10:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('protein_content', models.CharField(blank=True, max_length=50, verbose_name='protein content')),
                ('features', models.CharField(help_text='Comma separated features, e.g. Growth Focus, Milk Booster', max_length=255, verbose_name='features')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'feed type',
                'verbose_name_plural': 'feed types',
                'ordering': ['order'],
            },
        ),
    ]
