# Generated by Django 4.2 on 2026-01-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_feedtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='feedtype',
            name='image',
            field=models.ImageField(upload_to='feed_types/'),
        ),
    ]
