# Generated by Django 4.2 on 2026-01-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    # This migration was left behind when other migrations were reverted.
    # Convert it into a no-op migration that depends on 0001_initial so
    # the migration graph stays consistent in this development environment.
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = []
