# Generated by Django 4.2 on 2026-01-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_accounts_em_email_123456_idx_accounts_em_email_b3d765_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
