# Generated by Django 4.2 on 2026-01-11 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_additional_details_product_availability_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-priority', '-start_date']},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='offer',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Short label shown on product cards', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='offers', to='products.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_cart_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart value for cart offers', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('cart', 'Cart'), ('new_user', 'New user')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority offers are preferred'),
        ),
        migrations.AddField(
            model_name='offer',
            name='stackable',
            field=models.BooleanField(default=False, help_text='Whether this offer can stack with others'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='total_usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='usage_limit_per_user',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='user_eligibility',
            field=models.CharField(choices=[('all', 'All users'), ('logged_in', 'Logged-in users'), ('new', 'New users (first order)')], default='all', max_length=20),
        ),
    ]
