# Generated by Django 4.2 on 2026-01-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_tag_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
    ]
