# Generated by Django 4.2 on 2026-01-28 11:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_offer_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
